routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'shop', 'as' => 'product.'], function() {
    Route::get('index', 'ProductController@index')->name('index');
    Route::get('category/{taxonomyName}/', 'ProductController@index')->name('categories');
    Route::get('category/{taxonomyName}/{taxon}', 'ProductController@index')->name('category');
    Route::get('p/{product}', 'ProductController@show')->name('show');
});

Route::group(['prefix' => 'cart', 'as' => 'cart.'], function() {
    Route::get('show', 'CartController@show')->name('show');
    Route::post('add/{product}', 'CartController@add')->name('add');
    Route::post('update/{cart_item}', 'CartController@update')->name('update');
    Route::post('remove/{cart_item}', 'CartController@remove')->name('remove');
});

Route::group(['prefix' => 'checkout', 'as' => 'checkout.'], function() {
    Route::get('show', 'CheckoutController@show')->name('show');
    Route::post('submit', 'CheckoutController@submit')->name('submit');
});

app/Taxon.php
<?php

namespace App;

class Taxon extends \Vanilo\Category\Models\Taxon
{
    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Taxonomy.php
<?php

namespace App;

class Taxonomy extends \Vanilo\Category\Models\Taxonomy
{
//    public function getRouteKeyName()
//    {
//        return 'slug';
//    }
}

app/User.php
<?php

namespace App;

class User extends \Konekt\AppShell\Models\User
{
}

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Vanilo\Cart\Contracts\CartItem;
use Vanilo\Cart\Facades\Cart;
use Vanilo\Product\Contracts\Product;

class CartController extends Controller
{
    public function add(Product $product)
    {
        Cart::addItem($product);
        flash()->success($product->name . ' has been added to cart');

        return redirect()->route('cart.show');
    }

    public function remove(CartItem $cart_item)
    {
        Cart::removeItem($cart_item);
        flash()->info($cart_item->getBuyable()->getName() . ' has been removed from cart');

        return redirect()->route('cart.show');
    }

    public function update(CartItem $cart_item, Request $request)
    {
        $isItemInCurrentCart = false;
        foreach (Cart::getItems() as $item) {
            if ($item->id == $cart_item->id) {
                $isItemInCurrentCart = true;
                break;
            }
        }

        if (!$isItemInCurrentCart) {
            flash()->warning('Meeh!');
            return redirect()->route('cart.show');
        }

        $qty = (int) $request->get('qty', $cart_item->getQuantity());
        $cart_item->quantity = $qty;
        $cart_item->save();

        flash()->info(__(':cart_item has been updated', ['cart_item' => $cart_item->getBuyable()->getName()]));

        return redirect()->route('cart.show');
    }

    public function show()
    {
        return view('cart.show');
    }
}

app/Http/Controllers/CheckoutController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CheckoutRequest;
use Illuminate\Support\Facades\Auth;
use Konekt\Address\Models\CountryProxy;
use Vanilo\Cart\Contracts\CartManager;
use Vanilo\Checkout\Contracts\Checkout;
use Vanilo\Order\Contracts\OrderFactory;
use Vanilo\Order\Models\Order;

class CheckoutController extends Controller
{
    /** @var Checkout */
    private $checkout;

    /** @var Cart */
    private $cart;

    public function __construct(Checkout $checkout, CartManager $cart)
    {
        $this->checkout = $checkout;
        $this->cart     = $cart;
    }

    public function show()
    {
        $checkout = false;

        if ($this->cart->isNotEmpty()) {
            $checkout = $this->checkout;
            if ($old = old()) {
                $checkout->update($old);
            }

            $checkout->setCart($this->cart);
        }

        return view('checkout.show', [
            'checkout'  => $checkout,
            'countries' => CountryProxy::all()
        ]);
    }

    public function submit(CheckoutRequest $request, OrderFactory $orderFactory)
    {
        $this->checkout->update($request->all());
        $this->checkout->setCustomAttribute('notes', $request->get('notes'));
        $this->checkout->setCart($this->cart);

        /** @var Order $order */
        $order = $orderFactory->createFromCheckout($this->checkout);
        $order->getBillpayer()->email = Auth::user()->email;
        $order->getBillpayer()->save();
        $order->notes = $request->get('notes');
        $order->save();
        $this->cart->destroy();

        return view('checkout.thankyou', ['order' => $order]);
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Vanilo\Category\Models\TaxonomyProxy;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $taxonomies = TaxonomyProxy::get();
        return view('home',[
            'taxonomies' => $taxonomies,
        ]);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductIndexRequest;
use Vanilo\Category\Contracts\Taxon;
use Vanilo\Category\Models\TaxonomyProxy;
use Vanilo\Framework\Search\ProductFinder;
use Vanilo\Product\Contracts\Product;
use Vanilo\Properties\Models\PropertyProxy;

class ProductController extends Controller
{
    /** @var ProductFinder */
    private $productFinder;

    public function __construct(ProductFinder $productFinder)
    {
        $this->productFinder = $productFinder;
    }

    public function index(ProductIndexRequest $request, string $taxonomyName = null, Taxon $taxon = null)
    {
        $taxonomies = TaxonomyProxy::get();
        $properties = PropertyProxy::get();

        if ($taxon) {
            $this->productFinder->withinTaxon($taxon);
        }

        foreach ($request->filters($properties) as $property => $values) {
            $this->productFinder->havingPropertyValuesByName($property, $values);
        }

//        dd($taxonomies);
        return view('product.index', [
            'products'   => $this->productFinder->getResults(),
            'taxonomies' => $taxonomies,
            'taxon'      => $taxon,
            'properties' => $properties,
            'filters'    => $request->filters($properties)
        ]);
    }

    public function category(ProductIndexRequest $request, string $taxonomyName = null, Taxon $taxon = null)
    {
        $taxonomies = TaxonomyProxy::get();
        $properties = PropertyProxy::get();

        if ($taxon) {
            $this->productFinder->withinTaxon($taxon);
        }

        foreach ($request->filters($properties) as $property => $values) {
            $this->productFinder->havingPropertyValuesByName($property, $values);
        }

        return view('product.index', [
            'products'   => $this->productFinder->getResults(),
            'taxonomies' => $taxonomies,
            'taxon'      => $taxon,
            'properties' => $properties,
            'filters'    => $request->filters($properties)
        ]);
    }

    public function show(Product $product)
    {
        return view('product.show', ['product' => $product]);
    }
}

resources/views/cart/_summary.blade.php
<table class="table table-borderless table-condensed">
    <tr>
        <th class="pl-0">{{ __('Products') }}:</th>
        <td>{{ format_price(Cart::total()) }}</td>
    </tr>
</table>

<h5>{{ __('Total') }}:</h5>
<h3>{{ format_price(Cart::total()) }}</h3>

<hr>

resources/views/cart/show.blade.php
@extends('layouts.app')

@section('breadcrumbs')
    <li class="breadcrumb-item"><a href="{{ route('product.index') }}">{{ __('All Products') }}</a></li>
    <li class="breadcrumb-item">{{ __('Cart') }}</li>
@stop

@section('content')
    <style>
        .product-image {
            height: 45px;
        }
    </style>
    <div class="container">
        <h1>{{ __('Cart') }}</h1>
        <hr>

        @if(Cart::isEmpty())
            <div class="alert alert-info">
                {{ __('Your cart is empty') }}
            </div>
        @else
        <div class="row">
            <div class="col-md-8">
                <div class="card bg-light">
                    <div class="card-header">{{ __('Cart Items') }}</div>

                    <div class="card-body">
                        <div class="rounded bg-white">
                            <table class="table table-borderless">
                                <thead>
                                <tr>
                                    <th colspan="2">{{ __('Product Name') }}</th>
                                    <th>{{ __('Price') }}</th>
                                    <th>{{ __('Qty') }}</th>
                                    <th>{{ __('Total') }}</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach(Cart::getItems() as $item)
                                    <tr>
                                        <td width="55"><img src="{{ $item->product->getThumbnailUrl() ?: '/images/product.jpg' }}" class="product-image"/></td>
                                        <td>
                                            <a href="{{ route('product.show', $item->product) }}">
                                                {{ $item->product->getName() }}
                                            </a></td>
                                        <td>{{ format_price($item->price) }}</td>
                                        <td>
                                            <form class="form-inline" action="{{ route('cart.update', $item) }}" method="POST" id="cart-qty-form--{{ $item->id }}">
                                                @csrf
                                                <div class="input-group input-group-sm">
                                                    <div class="input-group-prepend">
                                                        <button class="btn btn-outline-secondary" type="button" data-itemid="{{ $item->id }}" data-role="cart-qty-changer" data-direction="-">-</button>
                                                    </div>
                                                    <input type="text" name="qty" value="{{ $item->quantity }}" class="form-control" id="cart-qty-input--{{ $item->id }}" />
                                                    <div class="input-group-append">
                                                        <button class="btn btn-outline-secondary" type="button" data-itemid="{{ $item->id }}" data-role="cart-qty-changer" data-direction="+">+</button>
                                                    </div>
                                                </div>

                                            </form>
                                        </td>
                                        <td>{{ format_price($item->total) }}</td>
                                        <td>
                                            <form action="{{ route('cart.remove', $item) }}"
                                                  style="display: inline-block" method="post">
                                                {{ csrf_field() }}
                                                <button dusk="cart-delete-{{ $item->getBuyable()->id }}" class="btn btn-link btn-sm"><span class="text-danger">&xotime;</span></button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th colspan="4"></th>
                                    <th>
                                        {{ format_price(Cart::total()) }}
                                    </th>
                                    <th></th>
                                </tr>
                                </tfoot>

                            </table>
                        </div>

                        <p>
                            <a href="{{ route('product.index') }}" class="btn-lg pl-0">{{ __('Continue Shopping') }}</a>
                        </p>

                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card bg-white">
                    <div class="card-header">{{ __('Summary') }}</div>
                    <div class="card-body">
                        @include('cart._summary')
                        <a href="{{ route('checkout.show') }}" class="btn btn-block btn-primary">{{ __('Proceed To Checkout') }}</a>
                    </div>
                </div>
            </div>
        </div>
        @endif
    </div>
@endsection

@section('scripts')
<script>
    $('document').ready(function () {
        $('button[data-role="cart-qty-changer"]').click(function () {
            itemid = $(this).data('itemid');
            $form = $('#cart-qty-form--' + itemid);
            $input = $('#cart-qty-input--' + itemid);
            currentQty = parseInt($input.val());
            qty = currentQty;
            if ('+' == $(this).data('direction')) {
                qty = currentQty + 1;
            } else if ('-' == $(this).data('direction')) {
                qty = currentQty - 1;
            } else {
                return; //do nothing if forged
            }

            $input.val(qty);
            $form.submit();
        });
    });
</script>
@endsection

resources/views/checkout/_billing_address.blade.php
<h3>Billing Address</h3>
<hr>

<div class="form-group row">
    <label class="col-form-label col-md-2">{{ __('Country') }}</label>
    <div class="col-md-10">
        {{ Form::select('billpayer[address][country_id]', $countries->pluck('name', 'id'),
                setting('appshell.default.country'), [
                'class' => 'form-control' . ($errors->has('billpayer.address.country_id') ? ' is-invalid' : '')
            ])
        }}

        @if ($errors->has('billpayer.address.country_id'))
            <div class="invalid-feedback">{{ $errors->first('billpayer.address.country_id') }}</div>
        @endif
    </div>
</div>

<div class="form-group row">

    <label class="col-form-label col-md-2">{{ __('Address') }}</label>
    <div class="col-md-10">
        {{ Form::text('billpayer[address][address]', null, [
                'class' => 'form-control' . ($errors->has('billpayer.address.address') ? ' is-invalid' : '')
            ])
        }}
        @if ($errors->has('billpayer.address.address'))
            <div class="invalid-feedback">{{ $errors->first('billpayer.address.address') }}</div>
        @endif
    </div>
</div>

<div class="form-group row">

    <label class="col-form-label col-md-2">{{ __('Zip code') }}</label>
    <div class="col-md-4">
        {{ Form::text('billpayer[address][postalcode]', null, [
                'class' => 'form-control' . ($errors->has('billpayer.address.postalcode') ? ' is-invalid' : '')
            ])
        }}
        @if ($errors->has('billpayer.address.postalcode'))
            <div class="invalid-feedback">{{ $errors->first('billpayer.address.postalcode') }}</div>
        @endif
    </div>

    <label class="col-form-label col-md-2">{{ __('City') }}</label>
    <div class="col-md-4">
        {{ Form::text('billpayer[address][city]', null, [
                'class' => 'form-control' . ($errors->has('billpayer.address.city') ? ' is-invalid' : '')
            ])
        }}
        @if ($errors->has('billpayer.address.city'))
            <div class="invalid-feedback">{{ $errors->first('billpayer.address.city') }}</div>
        @endif
    </div>

</div>

resources/views/checkout/show.blade.php
@extends('layouts.app')

@section('breadcrumbs')
    <li class="breadcrumb-item"><a href="{{ route('product.index') }}">All Products</a></li>
    <li class="breadcrumb-item"><a href="{{ route('cart.show') }}">Cart</a></li>
    <li class="breadcrumb-item">Checkout</li>

@stop

@section('content')
    <style>
        .product-image {
            max-width: 100%;
            display: block;
            margin-bottom: 2em;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Checkout</div>

                    <div class="card-body">
                        @unless ($checkout)
                            <div class="alert alert-warning">
                                <p>Hey, nothing to check out here!</p>
                            </div>
                        @endunless

                        @if ($checkout)
                            <form id="checkout" action="{{ route('checkout.submit') }}" method="post">
                                {{ csrf_field() }}

                                @include('checkout._billpayer', ['billpayer' => $checkout->getBillPayer()])

                                <div class="mb-4">
                                    <input type="hidden" name="ship_to_billing_address" value="0" />
                                    <div class="form-check">
                                        <input class="form-check-input" id="chk_ship_to_billing_address" type="checkbox" name="ship_to_billing_address" value="1" v-model="shipToBillingAddress">
                                        <label class="form-check-label" for="chk_ship_to_billing_address">Ship to the same address</label>
                                    </div>
                                </div>

                                @include('checkout._shipping_address', ['address' => $checkout->getShippingAddress()])

                                <hr>

                                <div class="form-group">

                                    <label class="">{{ __('Order Notes') }}</label>
                                    {{ Form::textarea('notes', null, [
                                            'class' => 'form-control' . ($errors->has('notes') ? ' is-invalid' : ''),
                                            'rows' => 3
                                        ])
                                    }}
                                    @if ($errors->has('notes'))
                                        <div class="invalid-feedback">{{ $errors->first('notes') }}</div>
                                    @endif
                                </div>

                                <hr>

                                <div>
                                    <button class="btn btn-lg btn-success">Submit Order</button>
                                </div>


                            </form>
                        @endif
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card bg-white">
                    <div class="card-header">Summary</div>
                    <div class="card-body">
                        @include('cart._summary')
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    @if ($checkout)
    <script>
        document.addEventListener("DOMContentLoaded", function(event) {
            new Vue({
                el: '#checkout',
                data: {
                    isOrganization: {{ old('billpayer.is_organization') ?: 0 }},
                    shipToBillingAddress: {{ old('ship_to_billing_address') ?? 1 }}
                }
            });
        });
    </script>
    @endif
@stop

resources/views/checkout/thankyou.blade.php
@extends('layouts.app')

@section('breadcrumbs')
    <li class="breadcrumb-item"><a href="{{ route('product.index') }}">All Products</a></li>
    <li class="breadcrumb-item"><a href="{{ route('cart.show') }}">Cart</a></li>
    <li class="breadcrumb-item">Checkout</li>
    <li class="breadcrumb-item">Order Complete</li>

@stop

@section('content')
    <div class="container">
        <h1>Wonderful {{ $order->getBillpayer()->firstname }}!</h1>
        <hr>

        <div class="alert alert-success">Your order has been registered with number
            <strong>{{ $order->getNumber() }}</strong>.
        </div>

        <h3>Next Steps</h3>

        <ol>
            <li>Your order will be prepared in the next 24 hours.</li>
            <li>Your package will be handed over to the courier.</li>
            <li>You'll receive an E-mail with the Shipment Information.</li>
        </ol>

        <div>
            <a href="{{ route('product.index') }}" class="btn btn-info">All right!</a>
        </div>

    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app_front')

@section('content')
    <div class="products-catagories-area clearfix">
        <div class="amado-pro-catagory clearfix">

            @foreach($taxonomies as $taxonomy)
            <div class="single-products-catagory clearfix">
                <a href="{{route('product.categories',['taxonomyName' => $taxonomy->slug])}}">
                    <img src="{{$taxonomy->getMedia()->first() ? $taxonomy->getMedia()->first()->getUrl('thumbnail') : 'img/bg-img/1.jpg';}}" alt="">
                    <!-- Hover Content -->
                    <div class="hover-content">
                        <div class="line"></div>
                        <p>From $180</p>
                        <h4>{{$taxonomy->name}}</h4>
                    </div>
                </a>
            </div>
            @endforeach
        </div>
    </div>
{{--    <!-- ##### jQuery (Necessary for All JavaScript Plugins) ##### -->--}}
{{--    <script src="js/jquery/jquery-2.2.4.min.js"></script>--}}
{{--    <!-- Popper js -->--}}
{{--    <script src="js/popper.min.js"></script>--}}
{{--    <!-- Bootstrap js -->--}}
{{--    <script src="js/bootstrap.min.js"></script>--}}
{{--    <!-- Plugins js -->--}}
{{--    <script src="js/plugins.js"></script>--}}
{{--    <!-- Active js -->--}}
{{--    <script src="js/active.js"></script>--}}
@endsection

resources/views/product/_breadcrumbs.blade.php
<?php
    $stack = [];
    $stack[] = [
        'url'   => route('product.category', [$taxon->taxonomy->slug, $taxon]),
        'label' => $taxon->name
    ];

    $parent = $taxon;
    while ($parent = $parent->parent) {
        $stack[] = [
            'url'   => route('product.category', [$parent->taxonomy->slug, $parent]),
            'label' => $parent->name
        ];
    }
    $stack[] = [
        'url'   => '#',
        'label' => $taxon->taxonomy->name
    ]
?>
@foreach(array_reverse($stack) as $item)
    <li class="breadcrumb-item"><a href="{{ $item['url'] }}">{{ $item['label'] }}</a></li>
@endforeach

resources/views/product/index.blade.php
@extends('layouts.app_front')

@section('categories-menu')
    <div class="shop_sidebar_area">

        <!-- ##### Single Widget ##### -->
        <div class="widget catagory mb-50">
            <!-- Widget Title -->
            <h6 class="widget-title mb-30">Catagories</h6>

            <!--  Catagories  -->
            <div class="catagories-menu">
                <ul>
                @foreach($taxonomies as $taxonomy)
                    <li class="active"><a href="{{route('product.categories',['taxonomyName' => $taxonomy->slug])}}">{{$taxonomy->name}}</a></li>
                @endforeach
                </ul>
            </div>
        </div>

        @include('product.index._filters', ['properties' => $properties, 'filters' => $filters])
    </div>

@stop


@section('content')
    <div class="container">
        <div class="row">

            <div class="col-md-3">
                @include('product.index._filters', ['properties' => $properties, 'filters' => $filters])
            </div>

            <div class="col-md-9">
                @if($taxon && $products->isEmpty() && $taxon->children->count())
                    <div class="card card-default mb-4">
                        <div class="card-header">{{ $taxon->name }} Subcategories</div>

                        <div class="card-body">
                            <div class="row">
                            @foreach($taxon->children as $child)
                                <div class="col-12 col-sm-6 col-md-4 mb-4">
                                    @include('product.index._category', ['taxon' => $child])
                                </div>
                            @endforeach
                            </div>
                        </div>
                    </div>
                @endif

                @if(!$products->isEmpty())
                <div class="card card-default">
                    <div class="card-header">{{ $taxon ?  'Products in ' . $taxon->name : 'All Products' }}</div>

                    <div class="card-body">
                        <div class="row">

                            @foreach($products as $product)
                                <div class="col-12 col-sm-6 col-md-4 mb-4">
                                    @include('product.index._product')
                                </div>
                            @endforeach

                        </div>
                    </div>
                </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/product/index/_category.blade.php
<article class="card shadow-sm">
    <div class="card-body">
        <h5><a href="{{ route('product.category', [$taxon->taxonomy->name, $taxon]) }}">{{ $taxon->name }}</a></h5>
    </div>
</article>

resources/views/product/index/_category_level.blade.php
@foreach($taxons as $taxon)
<div class="pl-{{$taxon->level}}">
    @if($taxon->children->count())
        <div class="dropdown-divider"></div>
        {{--<h6 class="dropdown-header">{{ $taxon->name }}</h6>--}}
        <a href="{{ route('product.category', [$taxon->taxonomy->slug, $taxon]) }}" class="dropdown-item dropdown-header">
            {{ $taxon->name }}
        </a>
        @include('product.index._category_level', ['taxons' => $taxon->children])
        <div class="dropdown-divider"></div>
    @else
        <a class="dropdown-item" href="{{ route('product.category', [$taxon->taxonomy->slug, $taxon]) }}">{{ $taxon->name }}</a>
    @endif
</div>
@endforeach

resources/views/product/index/_filters.blade.php
<form class="" action="{{
    $taxon ?
    route('product.category', [$taxon->taxonomy->slug, $taxon])
    :
    route('product.index')
}}">
    <ul class="list-group list-group-flush">
        @foreach($properties as $property)
            @include('product.index._property', ['property' => $property, 'filters' => $filters[$property->slug] ?? []])
        @endforeach
    </ul>
</form>

resources/views/product/index/_product.blade.php
<article class="card shadow-sm">
    <a href="{{ route('product.show', $product) }}">
        <img class="card-img-top"
        @if($product->hasImage())
            src="{{ $product->getThumbnailUrl() }}"
        @else
            src="/images/product.jpg"
        @endif
        alt="{{ $product->name }}" />
    </a>

    <div class="card-body">
        <h5><a href="{{ route('product.show', $product) }}">{{ $product->name }}</a></h5>
        <p class="card-text">{{ format_price($product->price) }}</p>
    </div>
</article>

resources/views/product/show.blade.php
@extends('layouts.app')

@section('breadcrumbs')
    <li class="breadcrumb-item"><a href="{{ route('product.index') }}">All Products</a></li>
    @if ($product->taxons->count())
        @include('product._breadcrumbs', ['taxon' => $product->taxons->first()])
    @endif
    <li class="breadcrumb-item">{{ $product->name }}</li>
@stop

@section('content')
    <style>
        .thumbnail-container {
            overflow-x: scroll;
        }

        .thumbnail {
            width: 64px;
            height: auto;
            display: block;
            float: left;
        }

        .thumbnail img {
            cursor: pointer;
        }
    </style>
    <div class="container">
        <h1>{{ $product->name }}</h1>
        <hr>

        <div class="row">
            <div class="col-md-6">
                <div class="mb-2">
                    <?php $img = $product->getMedia()->first() ? $product->getMedia()->first()->getUrl('medium') : '/images/product-medium.jpg' ?>
                    <img src="{{ $img  }}" id="product-image" />
                </div>

                <div class="thumbnail-container">
                    @foreach($product->getMedia() as $media)
                        <div class="thumbnail mr-1">
                            <img class="mw-100" src="{{ $media->getUrl('thumbnail') }}"
                                 onclick="document.getElementById('product-image').setAttribute('src', '{{ $media->getUrl("medium") }}')"
                            />
                        </div>
                    @endforeach
                </div>
            </div>

            <div class="col-md-6">
                <form action="{{ route('cart.add', $product) }}" method="post" class="mb-4">
                    {{ csrf_field() }}

                    <span class="mr-2 font-weight-bold text-primary btn-lg">{{ format_price($product->price) }}</span>
                    <button type="submit" class="btn btn-success btn-lg" @if(!$product->price) disabled @endif>Add to cart</button>
                </form>

                @unless(empty($product->propertyValues))
                <table class="table table-sm">
                    <tbody>
                    @foreach($product->propertyValues as $propertyValue)
                        <tr>
                            <th>{{ $propertyValue->property->name }}</th>
                            <td>{{ $propertyValue->title }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                @else
                    <hr>
                @endunless

                @unless(empty($product->description))
                <hr>
                <p class="text-secondary">{!!  nl2br($product->description) !!}</p>
                <hr>
                @endunless

            </div>
        </div>
    </div>
@endsection